#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' > sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
sudo service nginx start
