#!/usr/bin/env bash
# Installing a script that runs on a server
sudo apt-get update -y -qq && \
sudo apt-get upgrade -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
