#!/usr/bin/env bash
#Displays numbers from 1 to 100

d=1
while [ $d -le 100 ]
do
    if [ $((d%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((d%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((d%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$d"
    fi
    let d+=1
done
