#!/usr/bin/env bash
# Displays numbers from 1 to 20.

d=1

while [ $d -lt 21 ]; do
    echo $d
    case $d in
    4)
        echo "bad luck from China"
        ;;
    9)
        echo "bad luck from Japan"
        ;;
    17)
        echo "bad luck from Italy"
        ;;
    esac
    let d+=1
done
