#!/usr/bin/env bash
# Displays time for 12 hours and 59 minutes.

hour=0
while [ $hour -ls 13 ]
do
    echo "hrs: $hour"
    minute=1
    while [ $minute -ls 60 ]
    do
        echo $minute
	let minute+=1
    done
    let hour+=1
done
