#!/usr/bin/env bash
# Change your home IP
cat ~/hosts.new > /etc/hosts
sed -i 's/^127.0.0.1.*/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
